default_platform :ios
platform :ios do

## Setup CircleCI
  before_all do
    setup_circle_ci
  end

## Latest CircleCI build version number will be picked for testing
  lane :increment_build_num do
    increment_build_number(
      build_number: "$CIRCLE_BUILD_NUM",
      xcodeproj: "ios-dev-poc.xcodeproj"
    )
  end

## This step will search for existing 'Development and App Store Certififcates' in the Apple Developer Account. If found will use those else will create new ones.
  lane :use_cert do
    api_key = app_store_connect_api_key(
        key_id: "WXYFK8CF5D",
        issuer_id: "6701bcf4-21c5-4e25-9fd7-76af487a8e20",
        key_content: "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgz8S6G+oCbY+DlpDO44h91CyqPHc1f1hDIvO90XyVyi+gCgYIKoZIzj0DAQehRANCAATRh6sKuK3JunOpDqvb1xdkwZ3kbmiAueV/XaTNdZ/JNlbOW33ikt7yrA9jCDoukR0mqh1PisbBdCXuqJmmAkcC\n-----END PRIVATE KEY-----"
      )
      match(
        type: "development",
        readonly: false,
        force_for_new_devices: false,
        app_identifier: "com.neovasolutions.ios-dev-poc",
        git_url: "https://github.com/tarique-neova/ios-dev-poc.git",
      )

      match(
        type: "appstore",
        readonly: false,
        force_for_new_devices: false,
        app_identifier: "com.neovasolutions.ios-dev-poc",
        git_url: "https://github.com/tarique-neova/ios-dev-poc.git",
      )
  end       

## Build, Archive and Export .ipa file to output folder
  lane :build_release do |options|
        app_identifier = "com.neovasolutions.ios-dev-poc"       
        update_code_signing_settings(
          use_automatic_signing: false,
        )
       
        gym(
          scheme: "ios-dev-poc", # replace with name of your project’s scheme
          output_name: "neovapoc.ipa",
          configuration: "Release",
          xcargs: "-allowProvisioningUpdates",
          clean: true,
          export_options: {
            method: "app-store",
            provisioningProfiles: {
              app_identifier => "match AppStore com.neovasolutions.ios-dev-poc 1699360027" # here you can add any additional bundle identifiers and their associated provisioning profiles if you’re also building an app extension or other bundle identifier
            }
          }
        )
  end

## Deploy iOS app to TestFlight for internal tessting
  lane :testflight_internal_test do
    api_key = app_store_connect_api_key(
        key_id: "WXYFK8CF5D",
        issuer_id: "6701bcf4-21c5-4e25-9fd7-76af487a8e20",
        key_content: "-----BEGIN PRIVATE KEY-----\nMIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgz8S6G+oCbY+DlpDO44h91CyqPHc1f1hDIvO90XyVyi+gCgYIKoZIzj0DAQehRANCAATRh6sKuK3JunOpDqvb1xdkwZ3kbmiAueV/XaTNdZ/JNlbOW33ikt7yrA9jCDoukR0mqh1PisbBdCXuqJmmAkcC\n-----END PRIVATE KEY-----"
      )

   build_num = increment_build_number(
      build_number: "$CIRCLE_BUILD_NUM",
      xcodeproj: "ios-dev-poc.xcodeproj"
    )

    upload_to_testflight(
      build_number: build_num,
      api_key: api_key,
      app_identifier: "com.neovasolutions.ios-dev-poc",
      changelog: "Test POC App",
      ipa: "./output/gym/neovapoc.ipa",
      beta_app_review_info: {
        contact_email: "cloudsupport@neovasolutionss.com",
        contact_first_name: "Shashi",
        contact_last_name: "Ranjan",
        contact_phone: "+91 97634 45184",
        demo_account_name: "cloudsupport@neovasolutionss.com",
        demo_account_password: "Neova@123",
        notes: "this is review note for the reviewer <3 thank you for reviewing"
      },
      localized_app_info: {
        "en-US": {
          feedback_email: "cloudsupport@neovasolutionss.com",
          marketing_url: "https://doc-hosting.flycricket.io/ios-dev-poc-privacy-policy/1901553c-86cf-4dc3-89aa-6437658b47a8/privacy",
          privacy_policy_url: "https://doc-hosting.flycricket.io/ios-dev-poc-privacy-policy/1901553c-86cf-4dc3-89aa-6437658b47a8/privacy",
          description: "Default description"
        }
      },
      localized_build_info: {
        "en-US": {
          whats_new: "Default changelog"
        }
      }
    )
  end
end
